#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v

# -------------------------------------------------------------------------- #
# LibreOffice (version 4.0.4)                                                #
# -------------------------------------------------------------------------- #

APP="LibreOffice"
INSTALL_PATH="/Applications"
SOURCE="http://download.documentfoundation.org/libreoffice/stable/4.0.4/mac/x86/LibreOffice_4.0.4_MacOS_x86.dmg"

# Check for existing installation.
if [ "$INSTALL_PATH/$APP*" == "$INSTALL_PATH/$APP*" ]; then
    sudo rm -rf "$INSTALL_PATH/$APP*"
fi

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.dmg
hdiutil attach /tmp/"$APP"/Install.dmg
sudo cp -R /Volumes/"$APP"*/*.app $INSTALL_PATH/
hdiutil detach /Volumes/"$APP"*
rm -rf /tmp/"$APP"/
