#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v

# -------------------------------------------------------------------------- #
# Command-Line Tools (April 2013)                                            #
# -------------------------------------------------------------------------- #

APP="Command"
SOURCE="http://devimages.apple.com/downloads/xcode/command_line_tools_for_xcode_os_x_mountain_lion_april_2013.dmg"

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.dmg
hdiutil attach /tmp/"$APP"/Install.dmg
sudo installer -pkg /Volumes/"$APP"*/*.mpkg -tgt /
hdiutil detach /Volumes/"$APP"*
rm -rf /tmp/"$APP"/
