#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v


# -------------------------------------------------------------------------- #
# VirtualBox (version 4.2.16)                                                #
# -------------------------------------------------------------------------- #

APP="VirtualBox"
INSTALL_PATH="/Applications"
SOURCE="http://download.virtualbox.org/virtualbox/4.2.16/VirtualBox-4.2.16-86992-OSX.dmg"

# Check for existing installation.
if [ "$INSTALL_PATH/$APP*" == "$INSTALL_PATH/$APP*" ]; then
    sudo rm -rf "$INSTALL_PATH/$APP*"
fi

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.dmg
hdiutil attach /tmp/"$APP"/Install.dmg
sudo installer -pkg /Volumes/"$APP"*/*.pkg -tgt /
hdiutil detach /Volumes/"$APP"*
rm -rf /tmp/"$APP"/

# Set the default location for the VMs
VBoxManage setproperty machinefolder $HOME/Library/VirtualBox/Machines


# -------------------------------------------------------------------------- #
# Vagrant (version 1.2.2)                                                    #
# -------------------------------------------------------------------------- #

# Prompt for a password and extend the time stamp.
sudo -v

APP="Vagrant"
INSTALL_PATH="/Library/Bundles"
SOURCE="http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/Vagrant-1.2.2.dmg"

# Check for existing version.
if [ "$INSTALL_PATH/$APP*" == "$INSTALL_PATH/$APP*" ]; then
    sudo rm -rf "$INSTALL_PATH/$APP*"
fi

# Install.
mkdir -p $HOME/Library/Application\ Support/"$APP"/
ln -s $HOME/Library/Application\ Support/"$APP"/ $HOME/.gem
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.dmg
sudo -v
hdiutil attach /tmp/"$APP"/Install.dmg
sudo installer -pkg /Volumes/"$APP"*/*.pkg -tgt /
hdiutil detach /Volumes/"$APP"
sudo mv /Applications/"$APP" "$INSTALL_PATH/$APP.bundle"
sudo ln -sf "$INSTALL_PATH/$APP.bundle/bin/vagrant" /usr/bin/vagrant
sudo curl https://raw.github.com/BrianSpeir/Bundles/master/"$APP"/Resources/Info.plist -o "$INSTALL_PATH/$APP.bundle/Info.plist"

# Modify default_home_path to better suite Mac OS
sudo curl https://raw.github.com/BrianSpeir/Bundles/master/"$APP"/Resources/environment.rb -o "$INSTALL_PATH/$APP.bundle/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/environment.rb"
sudo chmod -R 755 "$INSTALL_PATH/$APP.bundle"
rm -rf /tmp/"$APP"/

# Install plug-ins
vagrant plugin install vagrant-aws
vagrant plugin install vagrant-rackspace
