#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v


# -------------------------------------------------------------------------- #
# VirtualBox                                                                 #
# -------------------------------------------------------------------------- #

# Version 4.2.10
curl -L "http://download.virtualbox.org/virtualbox/4.2.10/VirtualBox-4.2.10-84104-OSX.dmg" --create-dirs -o /tmp/VirtualBox/Install.dmg
hdiutil attach /tmp/VirtualBox/Install.dmg
sudo installer -pkg /Volumes/VirtualBox/VirtualBox.pkg -tgt /
hdiutil detach /Volumes/VirtualBox
rm -rf /tmp/VirtualBox/
# Set the default location for the VMs
VBoxManage setproperty machinefolder $HOME/Library/VirtualBox/Machines

# -------------------------------------------------------------------------- #
# Vagrant                                                                    #
# -------------------------------------------------------------------------- #

# Prompt for a password and extend the time stamp.
sudo -v

# Check for existing version.
APP="/Library/Bundles/Vagrant.bundle"
if [ "$APP" == "$APP" ]; then
    sudo rm -rf "$APP"
fi

# Version 1.1.5
mkdir -p $HOME/Library/Application\ Support/Vagrant/
ln -s $HOME/Library/Application\ Support/Vagrant/ $HOME/.gem
curl -L "http://files.vagrantup.com/packages/64e360814c3ad960d810456add977fd4c7d47ce6/Vagrant.dmg" --create-dirs -o /tmp/Vagrant/Install.dmg
hdiutil attach /tmp/Vagrant/Install.dmg
sudo installer -pkg /Volumes/Vagrant/Vagrant.pkg -tgt /
hdiutil detach /Volumes/Vagrant
sudo mv /Applications/Vagrant /Library/Bundles/Vagrant.bundle
sudo ln -sf /Library/Bundles/Vagrant.bundle/bin/vagrant /usr/bin/vagrant
sudo curl https://raw.github.com/BrianSpeir/Bundles/master/Vagrant/Resources/Info.plist -o /Library/Bundles/Vagrant.bundle/Info.plist
sudo curl https://raw.github.com/BrianSpeir/Bundles/master/Vagrant/Resources/environment.rb -o "/Library/Bundles/Vagrant.bundle/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb"
sudo chmod -R 755 /Library/Bundles/Vagrant.bundle
rm -rf /tmp/Vagrant/
# Plug-ins
vagrant plugin install vagrant-aws
vagrant plugin install vagrant-rackspace
