#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v

# -------------------------------------------------------------------------- #
# Chrome (version latest)                                                    #
# -------------------------------------------------------------------------- #

APP="Google Chr"
INSTALL_PATH="/Applications"
SOURCE="https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg"

# Check for existing installation.
if [ "$INSTALL_PATH/$APP*" == "$INSTALL_PATH/$APP*" ]; then
    sudo rm -rf "$INSTALL_PATH/$APP*"
fi

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.dmg
hdiutil attach /tmp/"$APP"/Install.dmg
sudo cp -R /Volumes/"$APP"*/*.app $INSTALL_PATH/
hdiutil detach /Volumes/"$APP"*
rm -rf /tmp/"$APP"/


# Opinions
# sudo mv $INSTALL_PATH"$APP"* $INChrome.app
sudo /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Chrome" $INSTALL_PATH/Google\ Chrome.app/Contents/Resources/en.lproj/InfoPlist.strings
#sudo /usr/libexec/PlistBuddy -c "Set :CFBundleName Chrome" $INSTALL_PATH/Google\ Chrome.app/Contents/Resources/en.lproj/InfoPlist.strings
