#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v

# -------------------------------------------------------------------------- #
# Firefox (version 22.0.0)                                                   #
# -------------------------------------------------------------------------- #

APP="Firefox"
INSTALL_PATH="/Applications"
SOURCE="http://download.mozilla.org/?product=firefox-22.0&os=osx&lang=en-US"

# Check for existing installation.
if [ "$INSTALL_PATH/$APP*" == "$INSTALL_PATH/$APP*" ]; then
    sudo rm -rf "$INSTALL_PATH/$APP*"
fi

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.dmg
hdiutil attach /tmp/"$APP"/Install.dmg
sudo cp -R /Volumes/"$APP"*/*.app $INSTALL_PATH/
hdiutil detach /Volumes/"$APP"*
rm -rf /tmp/"$APP"/
