#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v

# -------------------------------------------------------------------------- #
# Messages (proof of concept)                                                #
# -------------------------------------------------------------------------- #

APP="IRC"
INSTALL_PATH="/Library/Messages/PlugIns"
SOURCE="http://cdn.juicycocktail.com/download/IRC.imserviceplugin.zip"

# Check for existing installation.
if [ "$INSTALL_PATH/$APP*" == "$INSTALL_PATH/$APP*" ]; then
    sudo rm -rf "$INSTALL_PATH/$APP*"
fi

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.zip
sudo tar -xf /tmp/"$APP"/Install.zip -C $INSTALL_PATH/
rm -rf /tmp/"$APP"/
