#!/bin/bash
#

# Prompt for a password and extend the time stamp.
sudo -v

# -------------------------------------------------------------------------- #
# Projects Folder (version 1.0.0)                                            #
# -------------------------------------------------------------------------- #

APP="Projects-Folder"
INSTALL_PATH="$HOME"
SOURCE="https://github.com/BrianSpeir/Bundles/raw/master/Projects-Folder/Resources/Folder.zip"

# Install.
curl -L $SOURCE --create-dirs -o /tmp/"$APP"/Install.zip
ditto -xk /tmp/"$APP"/Install.zip $INSTALL_PATH/
rm -rf /tmp/"$APP"/
